config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :users, only: [:new, :create, :index, :show, :update] do
    get 'search', on: :collection
  end
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    resources :followings, only: [:create, :destroy]
    resources :patterns, only: [:create, :index, :show] do
      get 'groups/:id', on: :collection, to: 'patterns#groups'
    end
    resources :comments, only: [:create, :destroy]
    resources :learnings, only: [:create, :update, :destroy]
    resources :practices, only: [:create, :destroy]
  end
end

app/views/shared/_csrf.html.erb
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

app/views/shared/_form.html.erb
<div class="forms">
  <form class="<%= css_class %>" action="<%= action_url %>" method="post">
    <%= render 'shared/csrf' %>
    <input class="username" type="text" name="user[username]" value="<%= user.username %>" placeholder="Username">
    <% if action_url == users_url %>
      <input class="email" type="text" name="user[email]" value="<% user.email %>" placeholder="Email">
    <% end %>
    <input class="password" type="password" name="user[password]" placeholder="Password">
    <input type="hidden" name="user[guest]" value="false">
    <input class="submit" onclick="javascript:document.getElementById('o-loader').style.display='block';" type="submit" value="<%= action_text %>">
  </form>
  <form class="<% css_class %>" action="<%= users_url %>" method="post">
    <%= render 'shared/csrf' %>
    <input type="hidden" name="user[username]" value="<%= User.guest_username %>">
    <input type="hidden" name="user[email]" value="<%= User.guest_email %>">
    <input type="hidden" name="user[password]" value="password">
    <input type="hidden" name="user[guest]" value="true">
    <input class="submit guest" onclick="javascript:document.getElementById('o-loader').style.display='block';" type="submit" value="Log In as Guest">
  </form>
</div>

app/views/shared/_navbar.html.erb
<script charset="utf-8">
  function loading() {
    document.getElementById('o-loader').style.display = 'block';
  }
</script>

<nav class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a onclick="javascript:loading()" class="navbar-brand" href="#">jugglog</a>
      <div id="o-loader" class="loader">Loading...</div>
    </div>
    <% if !!current_user %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li class="patterns active">
          <a onclick="javascript:loading()" href="#patterns/1" >Patterns</a>
        </li>
        <li class="profile">
          <a
            onclick="javascript:loading()"
            href="<%= '#users/' + current_user.id.to_s %>"
          >Profile</a>
        </li>
        <li class="activity">
          <a onclick="javascript:loading()" href="#activity">Activity</a>
          </li>
        <li class="friends">
          <a onclick="javascript:loading()" href="#users">People</a>
        </li>
        <li class="info">
          <a onclick="javascript:loading()" href="#info">Info</a>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a onclick="javascript:loading()" class="name" href="javascript:void(0)" role="button">
            <%= current_user.username %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a
                onclick="javascript:loading()"
                href="<%= '#users/' + current_user.id.to_s %>"
              >Your Profile</a>
            </li>
            <li><%= link_to "Log Out", session_url, method: :delete %></li>
          </ul>
        </li>
        <!-- <li>
          <a onclick="javascript:loading()" href="#activity" >2 day streak</a>
        </li> -->
      </ul>
    <% else %>
      <% if request.fullpath == "/session/new" || request.fullpath == "/session" %>
        <ul class="nav navbar-nav navbar-right welcome">
          <li><%= link_to "Sign Up", new_user_url %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right welcome">
          <li><%= link_to "Log In", new_session_url %></li>
        </ul>
      <% end %>
    <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>